### ISSUE TITLE
Event during more of 2 days it's not showed correctly

### ISSUE THREAD

**Issue by acappelli** [alamkanak/Android-Week-View#86] opened 2015-03-02 14:50 UTC
Hi,
if I try to add an event that during more of 2 days this is not showed correctly.
Thanks in advance!
This is a screenshot with the code:
![schermata 2015-03-02 alle 15 45 33](https://cloud.githubusercontent.com/assets/1911447/6442939/d5664e44-c0f3-11e4-8115-bdb5639306c8.png)

**Comment by alamkanak** [comment] 2015-03-02 15:02
Duplicate of issue #75

**Closed by alamkanak** 2015-03-02 15:02 UTC
