### ISSUE TITLE
How to define a event duration 

### ISSUE THREAD

**Issue by jcmartins** [alamkanak/Android-Week-View#312] opened 2016-04-29 18:32 UTC
I would define a event time duration see exemple below:

12:00
12:45
13:00
13:45
14:00
14:45

**Comment by hova4** [comment] 2016-05-02 18:07
i want to know it too

**Comment by entropitor** [comment] 2016-05-04 19:02
I'm not getting the question?

(I'm closing this, because it's not a bug in the library. But feel free to explain a bit more)

**Closed as completed by entropitor** 2016-05-04 19:02 UTC

**Comment by jcmartins** [comment] 2016-05-05 18:42
It's not a bug maybe a feature? 
I would like to configure/set the interval time not full hour (60min) 
suppose 45minutes  
12:00
Soccer
12:45
NBA
13:30
NFL
14:15
suppose 120min
12:00
Soccer
14:00
NBA
16:00
NFL
18:00

**Comment by entropitor** [comment] 2016-05-09 07:19
You can just have events that have the appriopiate start and end time?

**Comment by jcmartins** [comment] 2016-05-09 20:45
I have an event each 45minutes and I like to show it.

**Comment by entropitor** [comment] 2016-05-09 21:33
Have you taken a look at the sample application?
