### ISSUE TITLE
How to restrict header day scroll for some specific days in week view calender

### ISSUE THREAD

**Issue by rohinisagar** [alamkanak/Android-Week-View#152] opened 2015-07-03 13:37 UTC
hiiii,
     I implement Android-week-view in my application. I want to restrict Day scroll Calendar between two date.

**Comment by caske33** [comment] 2015-07-05 15:20
duplicate of #29

**Comment by rohinisagar** [comment] 2015-07-21 06:34
I am try but scroll is stopped. I want to pass two date like 21/7/2015-25/7/2015 then weekview calandar scroll between only 21/7/2015 and 25/7/2015 .

**Comment by caske33** [comment] 2015-07-21 14:36
I know what you want, it's just not possible at the moment and there is already an issue open for that problem.

**Comment by alamkanak** [comment] 2015-07-29 00:55
Duplicate of #29

**Closed by alamkanak** 2015-07-29 00:55 UTC
