### ISSUE TITLE
Need an icon on each event

### ISSUE THREAD

**Issue by jkhanknysys** [alamkanak/Android-Week-View#243] opened 2015-12-31 10:27 UTC
Hi I am trying to add different set of icons in each event. can you tell me how can I do that?
![screenshot from 2015-12-31 15 29 20](https://cloud.githubusercontent.com/assets/10721102/12063602/4c15d6bc-afd3-11e5-9ddd-899b85f62a84.png)

**Comment by caske33** [comment] 2015-12-31 15:59
That's currently not possible. I guess you'll have to adapt the library for that. (The library is rather simple, so it should probably be straightforward).

**Comment by Tolriq** [comment] 2016-01-01 12:06
If I may this is currently the biggest problem of the library and reason for many fork and many duplicate work.

If I had more time I'd propose a PR but I guess as most it's easier to fork / modify than modify the core.

Anyway the problem is that library is too much tied between WeekViewEvent and the view.

There's no proper way to add fields to this and modify the display without a fork :(

What would be wonderful is that the WeekViewEvent is more abstract with some copy methods to handle multidays events.

And separate the event drawing code into things that can be overridden easily.

Personally I'd go to at least 2 methods, a method that draw the background  / color (that most won't override) and a method to fill the said rectangle passing a clipped canvas for example.

**Comment by caske33** [comment] 2016-01-01 12:19
@Tolriq The problem is that nodoby on this project really has to time to do implement this. While this is indeed one of the biggest flaws of the library, somebody from the community is going to have to stand up to implement it.

**Comment by Tolriq** [comment] 2016-01-01 12:22
Well I may try in future as I'll have more needs, but it will be API 14+ so not sure you'll accept things like that.

**Comment by caske33** [comment] 2016-01-01 13:26
I think we need to contact @alamkanak too for that decision.

But wouldn't it possible to have a backwardscompatible version so that 14+ is customizable and 14- is not?

**Comment by Tolriq** [comment] 2016-01-01 13:31
Everything is possible but as my time is quite limited I won't have time to test / maintain this backward compat so will not propose it if the PR comes from me sorry.

**Comment by caske33** [comment] 2016-01-03 10:08
I'm gonna close this one in favor of #217.

**Closed by caske33** 2016-01-03 10:08 UTC

**Comment by vermotr** [comment] 2016-01-24 22:45
I created a PR that adds this functionality https://github.com/alamkanak/Android-Week-View/pull/266 ;-)
