### ISSUE TITLE
Showing All Day Events in a single cell at the top instead of drawing throughout the day column?

### ISSUE THREAD

**Issue by wwahmed** [alamkanak/Android-Week-View#228] opened 2015-12-13 06:33 UTC
Is it possible to set an Event as 'All Day' Event and have it be shown at the top of the day column (similar to google calendar) instead of occupying an event block throughout that column (and as a consequence, making all the other events small).?

Thanks

**Comment by caske33** [comment] 2015-12-13 11:18
Duplicate of #101

**Closed by caske33** 2015-12-13 11:18 UTC
