### ISSUE TITLE
Adding events of Single day from Back end dynamically

### ISSUE THREAD

**Issue by dev01-adroitinfosol** [alamkanak/Android-Week-View#251] opened 2016-01-04 06:56 UTC
First of all, i would like to say that this is an awesome app with perfect functionalities.

I have requirements of loading events of single day.. meaning that each time i change the day, new events are loaded from back-end and should be reflected on the view.

How do i achieve this?

Can u add default support for this functionality? or Can u give me somewhat details about how to achieve this?

Thanking you..

**Comment by entropitor** [comment] 2016-01-04 10:28
You can have a custom [WeekViewLoader](https://github.com/alamkanak/Android-Week-View/blob/develop/library/src/main/java/com/alamkanak/weekview/WeekViewLoader.java). Also take a look at the [MonthLoader implementatoin](https://github.com/alamkanak/Android-Week-View/blob/develop/library/src/main/java/com/alamkanak/weekview/MonthLoader.java)

You can for example take the time since UNIX epoch divided by `1000*60*60*24` for the periodIndex (the whole part of the periodIndex is then the amount of days since UNIX epoch, the fractional part is the percentage of the day that has passed). In this case the fractional part won't do anything, but normally it will be used to determine when to prefetch the next period.

Example code: (not 100% sure if it compiles, also a setter, getter and constructor for the listener are missing but see the MonthLoader). Hopefully you get the idea from this. As for the Async loading, see https://github.com/alamkanak/Android-Week-View/issues/18#issuecomment-61244158

``` java
public class DayLoader implements WeekViewLoader {
    double toWeekViewPeriodIndex(Calendar instance){
         return instance.getTimeInMillis()/(1000.0*60*60*24);
    }

    List<? extends WeekViewEvent> onLoad(int periodIndex){
        Calendar day = Calendar.getInstance().setTimeInMillis(periodIndex*(1000*60*60*24));
        return mDayChangeListener.onDayChange(day.get(Calendar.YEAR), day.get(Calendar.MONTH), day.get(Calendar.DAY_OF_MONTH))
    }
    private DayChangeListener mDayChangeListener;

    public interface DayChangeListener {
        List<? extends WeekViewEvent> onDayChange(int year, int month, int dayOfMonth);
    }
}
```

(I'm closing this because it's not a bug in the library, but if you have more questions, you can continue discussing it here).

**Closed by entropitor** 2016-01-04 10:28 UTC

**Comment by sm-tester** [comment] 2016-01-29 05:40
Hi Alam Kanak!

```
public class DayLoader implements WeekViewLoader {

private DayChangeListener mDayChangeListener;

@Override
public double toWeekViewPeriodIndex(Calendar instance) {
    return instance.getTimeInMillis()/(1000.0*60*60*24);
}

@Override
public List<? extends WeekViewEvent> onLoad(int periodIndex) {
    Calendar day = Calendar.getInstance();
    day.setTimeInMillis(periodIndex);
    return mDayChangeListener.onDayChange(day.get(Calendar.YEAR), day.get(Calendar.MONTH), day.get(Calendar.DAY_OF_MONTH));
}

public DayChangeListener getDayChangeListener() {
    return mDayChangeListener;
}

public void setDayChangeListener(DayChangeListener mDayChangeListener) {
    this.mDayChangeListener = mDayChangeListener;
}

public interface DayChangeListener {
    List<? extends WeekViewEvent> onDayChange(int year, int month, int dayOfMonth);
}
}
```

If you using this class with WeekView library, when library called to the callback "onDayChange" I will be get following year, month and day :  

```
01-29 10:32:28.227 I/WCalendarPage: onDayChange ---------> year : 1970 month :0 dayOfMonth : 1
01-29 10:32:28.228 I/WCalendarPage: onDayChange ---------> year : 1970 month :0 dayOfMonth : 1
01-29 10:32:28.228 I/WCalendarPage: onDayChange ---------> year : 1970 month :0 dayOfMonth : 1
```

You can see incorrect date : 01.00.1970 . Can you give me any suggestion. I tried change code in method: 

```
@Override
public List<? extends WeekViewEvent> onLoad(int periodIndex) {
    Calendar day = Calendar.getInstance();
    day.setTimeInMillis(periodIndex);
    return mDayChangeListener.onDayChange(day.get(Calendar.YEAR),day.get(Calendar.MONTH),
    day.get(Calendar.DAY_OF_MONTH));
}
```

to

```
@Override
public List<? extends WeekViewEvent> onLoad(int periodIndex) {
    Calendar day = Calendar.getInstance();
    day.setTimeInMillis(periodIndex * (1000.0*60*60*24));
    return mDayChangeListener.onDayChange(day.get(Calendar.YEAR),day.get(Calendar.MONTH),
    day.get(Calendar.DAY_OF_MONTH));
}
```

but, not helped.

**Comment by entropitor** [comment] 2016-01-29 11:57
@boyfox I'm sorry, I see that there was a bug in my code snippet. Can you try

``` java
List<? extends WeekViewEvent> onLoad(int periodIndex){
        Calendar day = Calendar.getInstance().setTimeInMillis(periodIndex*(1000*60*60*24));
        return mDayChangeListener.onDayChange(day.get(Calendar.YEAR), day.get(Calendar.MONTH), day.get(Calendar.DAY_OF_MONTH))
    }
```

(you have to multiply the periodIndex with `(1000*60*60*24)` again in onLoad).

**Comment by sm-tester** [comment] 2016-01-29 14:29
I solved problem with following way : 

public class DayLoader implements WeekViewLoader {

```
    private DayChangeListener mDayChangeListener;

    private int lastPeriodIndex;
    private Calendar lastCalendar;

    @Override
    public double toWeekViewPeriodIndex(Calendar instance) {
        double periodIndex = instance.getTimeInMillis() / (1000.0 * 60 * 60 * 24);
        lastPeriodIndex = (int) periodIndex;
        lastCalendar = instance;
        return periodIndex;
    }

    @Override
    public List<? extends WeekViewEvent> onLoad(int periodIndex) {
        Calendar day = null;
        int diffDays = lastPeriodIndex - periodIndex;
        if (diffDays == 0) {
            day = lastCalendar;
        } else {
            day = (Calendar) lastCalendar.clone();
            day.add(Calendar.DAY_OF_MONTH, -1 * diffDays);
        }
        return mDayChangeListener.onDayChange(day.get(Calendar.YEAR), day.get(Calendar.MONTH),
                day.get(Calendar.DAY_OF_MONTH));
    }

    public DayChangeListener getDayChangeListener() {
        return mDayChangeListener;
    }

    public void setDayChangeListener(DayChangeListener mDayChangeListener) {
        this.mDayChangeListener = mDayChangeListener;
    }

    public interface DayChangeListener {
        List<? extends WeekViewEvent> onDayChange(int year, int month, int dayOfMonth);
    }
}
```

**Comment by entropitor** [comment] 2016-01-29 16:11
@boyfox If this works, super!

(But be aware that this is not according to the semantics of the library, so this might break in the future!)

**Comment by sm-tester** [comment] 2016-01-30 06:23
@caske33 yes you are absolutely right, I hope you it takes into account in future releases of library. I hope you will be add daily, thirdly, weekly loading data styles and customizations event rectangle style!
