### ISSUE TITLE
why Events are repeating every months

### ISSUE THREAD

**Issue by anirbansAndroidDev** [alamkanak/Android-Week-View#140] opened 2015-06-14 20:48 UTC
I need to show events weekly basis. But If how can I create a event on a particulate date month time? and why events are repeating every months. 

What I tried to add a event on a particulate date and time - 

Calendar startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, 3);
        startTime.set(Calendar.MINUTE, 0);
        startTime.set(Calendar.MONTH, 6);
        startTime.set(Calendar.YEAR, 2015);
        Calendar endTime = (Calendar) startTime.clone();
        endTime.add(Calendar.HOUR, 2);
        endTime.set(Calendar.MONTH, 06);
        WeekViewEvent event = new WeekViewEvent(1, getEventTitle(startTime), startTime, endTime);
        event.setColor(getResources().getColor(R.color.event_color_01));
        event.setName("Meeting with John");
        events.add(event);

But nothing happening.

**Comment by lolobosse** [comment] 2015-06-15 10:22
Can you show your entire code ? That seems correct but I think the problem is how you add to the view... Where is this code written?

**Comment by anirbansAndroidDev** [comment] 2015-06-15 10:47
I added this code in OnCreate instead of on month change. So that I can skip the event repeating every months. 

The thing I figure it out onMonthChange all events are creating so each and every months it's adding same event on same time. But I need to add a single event in a single date and time it shoild not repeat.

**Comment by caske33** [comment] 2015-06-15 11:01
@anirbansAndroidDev Are you using those code samples? Or are you replacing the numbers with variables?

Because you have to keep in mind that the parameters passed to onMonthChange are the month and year of the month that is requested. So if you use those parameters for setting the month on the event, the event will occur in every month.

And if you're setting this in onCreate, how are you passing the events to the library?

**Comment by anirbansAndroidDev** [comment] 2015-06-15 13:18
@caske33 as per you I am doing this in onMonthChange 

```java
        Calendar startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, 6);
        startTime.set(Calendar.MINUTE, 0);
        startTime.set(Calendar.DATE, 16);
        startTime.set(Calendar.MONTH, 6);
        startTime.set(Calendar.YEAR, 2015);
        Calendar endTime = (Calendar) startTime.clone();
        endTime.set(Calendar.HOUR_OF_DAY, 7);
        endTime.set(Calendar.MINUTE, 30);
        endTime.set(Calendar.DATE, 16);
        endTime.set(Calendar.MONTH, 6);
        endTime.set(Calendar.YEAR, 2015);
        WeekViewEvent event = new WeekViewEvent(1, getEventTitle(startTime), startTime, endTime);
        event.setColor(getResources().getColor(R.color.event_color_01));
        event.setName("Meeting with John");
        events.add(event); 
```

But nothing is showing.

**Comment by caske33** [comment] 2015-06-15 13:32
But what are you doing with your `events`? You have to return the `events`-list in the onMonthChange method, otherwise the library won't know about the events.

**Comment by anirbansAndroidDev** [comment] 2015-06-15 13:34
Yes I do. Look the full code - 
```java
    @Override
    public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {

        // Populate the week view with some events.
        List<WeekViewEvent> events = new ArrayList<WeekViewEvent>();

        Calendar startTime = Calendar.getInstance();
        startTime.set(Calendar.HOUR_OF_DAY, 6);
        startTime.set(Calendar.MINUTE, 0);
        startTime.set(Calendar.DATE, 16);
        startTime.set(Calendar.MONTH, 6);
        startTime.set(Calendar.YEAR, 2015);
        Calendar endTime = (Calendar) startTime.clone();
        endTime.set(Calendar.HOUR_OF_DAY, 7);
        endTime.set(Calendar.MINUTE, 30);
        endTime.set(Calendar.DATE, 16);
        endTime.set(Calendar.MONTH, 6);
        endTime.set(Calendar.YEAR, 2015);
        WeekViewEvent event = new WeekViewEvent(1, getEventTitle(startTime), startTime, endTime);
        event.setColor(getResources().getColor(R.color.event_color_01));
        event.setName("Meeting with John");
        events.add(event);

        return events;
    }
```

**Comment by caske33** [comment] 2015-06-15 13:37
You should be aware that the Calendar.MONTH starts at 0. So this event is on 16 July, not June. Can you take a look if the event appears in July?

**Comment by anirbansAndroidDev** [comment] 2015-06-15 13:39
Yes you are right @caske33 But it looks like this why so?

![screenshot_2015-06-15-19-08-22](https://cloud.githubusercontent.com/assets/3717875/8161085/09742418-1392-11e5-9bbc-209c9df5ab57.png)

**Comment by anirbansAndroidDev** [comment] 2015-06-15 13:51
Updated the image

**Comment by caske33** [comment] 2015-06-15 14:02
See #81

**Comment by lolobosse** [comment] 2015-06-15 14:12
@caske33 Can you close the issues yet? (do you have right access?). I can't send you message directly on Github that's why I'm asking here and also because you should close this issue.

**Comment by caske33** [comment] 2015-06-15 14:16
No, I don't have the access yet. This should be closed indeed.

**Closed** 2015-06-15 14:18 UTC

**Comment by anirbansAndroidDev** [comment] 2015-06-15 14:20
How should I check  `month matches with your event` ?

**Comment by anirbansAndroidDev** [comment] 2015-06-15 15:16
Tried this code but same issue https://github.com/Quivr/Android-Week-View

**Comment by caske33** [comment] 2015-06-15 18:49
@anirbansAndroidDev the issue doesn't lie within the library, it's an issue with your code. As explained in https://github.com/alamkanak/Android-Week-View/issues/81#issuecomment-75428905

>The onMonthChange is called three times: One time for this month and then one time for the previous and next month (for smooth scrolling). Because you're providing the events three times, they are rendered three times.

>(you should only return the events that fall within the month that is requested, based on the arguments passed in onMonthChange)

**Comment by anirbansAndroidDev** [comment] 2015-06-15 18:59
How can I achieve that?

**Comment by lolobosse** [comment] 2015-06-15 19:36
Just read the sample code! You just have to return the elements corresponding of the given month of the onMonthChange(int year, int month)

**Comment by anirbansAndroidDev** [comment] 2015-06-15 19:44
Yes I got it @lolobosse . Thanks a lot @caske33 

Code looks like this - 

```java
@Override
    public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {

        // Populate the week view with some events.
        List<WeekViewEvent> events = new ArrayList<WeekViewEvent>();

        if(newMonth == 5) {
            Calendar startTime = Calendar.getInstance();
            startTime.set(Calendar.HOUR_OF_DAY, 6);
            startTime.set(Calendar.MINUTE, 0);
            startTime.set(Calendar.DATE, 16);
            startTime.set(Calendar.MONTH, 5);
            startTime.set(Calendar.YEAR, 2015);
            Calendar endTime = (Calendar) startTime.clone();
            endTime.set(Calendar.HOUR_OF_DAY, 7);
            endTime.set(Calendar.MINUTE, 30);
            endTime.set(Calendar.DATE, 16);
            endTime.set(Calendar.MONTH, 5);
            endTime.set(Calendar.YEAR, 2015);
            WeekViewEvent event = new WeekViewEvent(1, getEventTitle(startTime), startTime, endTime);
            event.setColor(getResources().getColor(R.color.event_color_01));
            event.setName("Meeting with John");
            events.add(event);
        }
        return events;
    }
```

**Comment by lolobosse** [comment] 2015-06-15 21:52
:+1:

**Comment by caske33** [comment] 2015-06-16 10:35
@anirbansAndroidDev the newMonth if-statement should probably be `newMonth == 6`, as the newMonth parameter is 1-based instead of the 0-based Calendar API.

**Comment by haithamay** [comment] 2017-12-25 15:03
Hi,
I'm trying to show events from FirebaseDatabase as the following, but it doesn't show.
Any help please.

public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {

        final Calendar startOfMonth = Calendar.getInstance();
        startOfMonth.set(Calendar.YEAR, newYear);
        startOfMonth.set(Calendar.MONTH, newMonth - 1);
        startOfMonth.set(Calendar.DAY_OF_MONTH, 1);
        startOfMonth.set(Calendar.HOUR_OF_DAY, 0);
        startOfMonth.set(Calendar.MINUTE, 0);
        startOfMonth.set(Calendar.SECOND, 0);
        startOfMonth.set(Calendar.MILLISECOND, 0);
        final Calendar endOfMonth = (Calendar) startOfMonth.clone();
        endOfMonth.set(Calendar.DAY_OF_MONTH, 
        endOfMonth.getMaximum(Calendar.DAY_OF_MONTH));
        endOfMonth.set(Calendar.HOUR_OF_DAY, 23);
        endOfMonth.set(Calendar.MINUTE, 59);
        endOfMonth.set(Calendar.SECOND, 59);

        //get events from firebase database
        final List<WeekViewEvent> matchedEvents = new ArrayList<WeekViewEvent>();
        final List<EventHelper> eventsFromFireBase = new ArrayList<EventHelper>();
        final long[] id = {0};
        final String[] eventName = new String[1];
        final String[] location = new String[1];
        final SimpleDateFormat[] sdf = new SimpleDateFormat[1];
        final WeekViewEvent[] weekViewEvent = new WeekViewEvent[1];
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        DatabaseReference databaseReference = database.getReference();
        databaseReference.child("events").addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                Log.e("Count " ,""+dataSnapshot.getChildrenCount());
                for (DataSnapshot postSnapshot: dataSnapshot.getChildren()) {
                    EventHelper ev = postSnapshot.getValue(EventHelper.class);
                    eventsFromFireBase.add(ev);
                    Log.d("eventHelper", ev.getmName().toString());
                    Log.d("eventHelper", ev.getmLocation().toString());
                    Log.d("eventHelper", ev.getmStartTime().toString());
                    Log.d("eventHelper", ev.getmEndTime().toString());
                }
                for (EventHelper ev : eventsFromFireBase) {
                    Calendar cal1 = Calendar.getInstance(), cal2 = Calendar.getInstance();
                    id[0] = ev.getId();
                    eventName[0] = ev.getmName();
                    location[0] = ev.getmLocation();
                    sdf[0] = new SimpleDateFormat("EEE dd/MM/yyyy HH:MM:SS");
                    try {
                        cal1.setTime(sdf[0].parse(ev.getmStartTime()));
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                    try {
                        cal2.setTime(sdf[0].parse(ev.getmEndTime()));
                    } catch (ParseException e) {
                        e.printStackTrace();
                    }
                    if (cal2.getTimeInMillis() > startOfMonth.getTimeInMillis() &&
                            cal1.getTimeInMillis() < endOfMonth.getTimeInMillis()) {
                        weekViewEvent[0] = new WeekViewEvent(id[0], eventName[0], location[0], cal1, cal2);
                        rnd = new Random();
                        int x = rnd.nextInt(6);
                        switch (x) {
                            case 0:
                                weekViewEvent[0].setColor(getResources().getColor(R.color.event_color_01));
                                break;
                            case 1:
                                weekViewEvent[0].setColor(getResources().getColor(R.color.event_color_02));
                                break;
                            case 2:
                                weekViewEvent[0].setColor(getResources().getColor(R.color.event_color_03));
                                break;
                            case 3:
                                weekViewEvent[0].setColor(getResources().getColor(R.color.event_color_04));
                                break;
                            case 4:
                                weekViewEvent[0].setColor(getResources().getColor(R.color.event_color_05));
                                break;
                            case 5:
                                weekViewEvent[0].setColor(getResources().getColor(R.color.event_color_06));
                                break;
                        }
                        matchedEvents.add(weekViewEvent[0]);
                    }
                }
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });
          
    return matchedEvents;
    }
