### ISSUE TITLE
how to limit scrolling to one month ?

### ISSUE THREAD

**Issue by Hariharanswamy** [alamkanak/Android-Week-View#111] opened 2015-04-16 09:22 UTC
i want to horizontal scrolling to one month.. how can i achieve this ?

**Comment by caske33** [comment] 2015-04-16 10:50
duplicate of #6

**Comment by Hariharanswamy** [comment] 2015-04-16 10:55
@caske33 it is to limit only one week... i want to limit for a month.. and it is dynamically.. sometimes more than a month

**Comment by caske33** [comment] 2015-04-16 15:17
I meant #29 then. It's a known issue, but it doesn't have a solution currently.

**Comment by alamkanak** [comment] 2015-04-16 16:08
Duplicate of #29

**Closed by alamkanak** 2015-04-16 16:08 UTC
