### ISSUE TITLE
 onMonthChange Listener calling 3 times every time i launch the app, is there any way to call only once 

### ISSUE THREAD

**Issue by kprathap23** [alamkanak/Android-Week-View#212] opened 2015-11-23 13:51 UTC
@Override
    public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {

        // Populate the Month Appointments from web service for single month and added events to            //allCalendarEvents object 

         return allCalendarEvents; // declared globally 
    }

**Comment by caske33** [comment] 2015-11-23 16:39
Duplicate of #81. See answers there.

**Closed by caske33** 2015-11-23 16:39 UTC
