### ISSUE TITLE
goToDate doesn't work properly when changing view type

### ISSUE THREAD

**Issue by josefrvaldes** [alamkanak/Android-Week-View#65] opened 2015-02-02 11:19 UTC
Hello, I've noticed that when you change the type of view from three days to one day, for example, it goes to today.
As I want that it remains in the same day that it was, I'm trying to do the next: 

// 
case R.id.action_day_view:
                if (mWeekViewType != TYPE_DAY_VIEW) {
                    item.setChecked(!item.isChecked());
                    mWeekViewType = TYPE_DAY_VIEW;
                    mWeekView.setNumberOfVisibleDays(1);

                    // Cambiamos las medidas.
                    mWeekView.setColumnGap((int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 8, getResources().getDisplayMetrics()));
                    mWeekView.setTextSize((int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_SP, 12, getResources().getDisplayMetrics()));
                    mWeekView.setEventTextSize((int) TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_SP, 12, getResources().getDisplayMetrics()));
                    
                     mWeekView.goToDate(previousSelectedDate);
                }
                return true;

but this doesn't work as expected. It doesn't go to that date, and it goes to the middle between today, and the date I want to go.

**Comment by caske33** [comment] 2015-02-02 19:33
The problem is that goToDate uses the margins from the last time the weekview was drawn. 

However I think the problem can be fixed with (a slight modification of) #53

**Comment by josefrvaldes** [comment] 2015-02-02 19:45
So.. what can I do now? 
I've noticed that you have made some

**Comment by josefrvaldes** [comment] 2015-02-02 19:47
So.. what can I do now? Can I fix it?
I've read that you have fix a lot of issues, and event implemented a scrolledListener, but I can't still use it. When will I be able to use it?

Sorry by my English, I'm from Spain.

**Comment by caske33** [comment] 2015-02-02 20:10
I can maybe take a look at it tomorrow. It depends. @alamkanak is the only one who can make releases though, so you'll definitly have to wait for him to release the code anyway.

**Comment by josefrvaldes** [comment] 2015-02-02 20:12
Ok! thank you very much!! don't worry, I'll wait!!
We both will have to wait to @alamkanak!! :P

**Comment by alamkanak** [comment] 2015-02-02 22:48
Hey guys I am really sorry for being late. The thing is I recently caught jaundice. And my doctor asked me to take complete bed rest until I fully recover. I can barely stand up straight these days. So I will get back to all of you as soon as I recover.

**Comment by josefrvaldes** [comment] 2015-02-02 22:50
Don't worry friend, please get better!! we'll be here waiting for you! :)

**Comment by caske33** [comment] 2015-02-03 11:47
what jose said

**Closed** 2015-03-01 15:49 UTC
