### ISSUE TITLE
Event in cycle

### ISSUE THREAD

**Issue by hova4** [alamkanak/Android-Week-View#317] opened 2016-05-07 18:53 UTC
can i make an event for every week ?
i need to display an event on Monday in every week,,, i try a lot of code, but there is no result,,, please if you know how to do that, help me

**Comment by entropitor** [comment] 2016-05-09 07:16
Duplicate of #38.

Just return multiple instances of the same event, one for every monday for example.

**Closed as completed by entropitor** 2016-05-09 07:16 UTC
Labels: duplicate

**Comment by hova4** [comment] 2016-05-09 09:57
i saw that issue, but i have trouble with it. Can you give me some code, please. I would be very thankful
