### ISSUE TITLE
Limit the days to only one week

### ISSUE THREAD

**Issue by lazarnikolov94** [alamkanak/Android-Week-View#85] opened 2015-03-01 14:43 UTC
How can I limit the view to display only one week? I don't want to display the whole year in days, just one week, doesn't matter which date it is. I'm making a student timetable, that's why I don't need different dates, just 7 days, from Monday to Sunday, so the students can add their events and view them without scrolling.

**Comment by caske33** [comment] 2015-03-01 15:54
You can set the number of visible days to 7, if that is what you mean.

**Comment by lazarnikolov94** [comment] 2015-03-01 19:34
No I'd like to show only seven days. One week, that's all. No dates. I don't need 2 weeks because the students will enter the time and day of the subject, so they can keep track of their studies.

**Comment by alanlai1989** [comment] 2015-08-06 03:14
I want the horizontal scroll view only display the number of day that set by programmatically.
eg: 7 days so scrollview is from today until today + 7 days
today - 7 days until today

**Comment by caske33** [comment] 2015-08-06 18:19
This seems like a duplicate of #6. Currently, it isn't possible yet without modifying the source code of the library yourself.

**Closed by caske33** 2015-08-06 18:19 UTC
Labels: enhancement
