### ISSUE TITLE
Show only the days of the week (Sunday to Saturday)

### ISSUE THREAD

**Issue by anobilisgorse** [alamkanak/Android-Week-View#155] opened 2015-07-15 14:25 UTC
Is there other way to show only ONE WEEK, featuring the days 
(Sunday - Monday - Tuesday - Wednesday - Thursday - Friday - Saturday), as the header columns, and no specified dates?

**Comment by caske33** [comment] 2015-07-15 14:33
Duplicate of #6

**Comment by anobilisgorse** [comment] 2015-07-15 14:38
Actually I've encountered this awhile ago @caske33, but how do I replace it with the default Android-Week-View library? 

And also will it also cause some conflicts and exceptions with the current version of Android-Week-Library? I tried contacting the author of the repository but he seems inactive already.

**Comment by caske33** [comment] 2015-07-15 14:42
There is currently no support for this in this library.

**Comment by anobilisgorse** [comment] 2015-07-15 14:57
I see. That's sad.

**Comment by marunjar** [comment] 2015-07-15 16:21
maybe there's a possibility, haven't tested but it may work.

by setting xScrollingSpeed to 0 and noOfVisibleDays to 7 you should get a view that shows 7 days and cant scroll any more. 


for the names of days you can use your own DateTimeInterpreter using EEEE or EEE only in interpretDate

    @Override
    public String interpretDate(Calendar date) {
    	return new SimpleDateFormat("EEEE").format(date.getTime());
    }

the only thing left to do is to use goToDate an select the right date

**Comment by caske33** [comment] 2015-07-15 16:25
does setting xScrollingSpeed to 0 work, @marunjar ?

**Comment by anobilisgorse** [comment] 2015-07-15 16:55
Where and how do I set the xScrollingSpeed @marunjar?

**Comment by caske33** [comment] 2015-07-15 16:56
it's an attribute on the weekView.

**Comment by anobilisgorse** [comment] 2015-07-15 16:58
I see, I'll try this. 

Regarding the goToDate @marunjar, what do you mean by "select the right date"? Date refers to the numbers right, so I am confused as to why I need to set this, cause I only need the DAYS (Sunday to Saturday). Please elaborate it further.

**Comment by caske33** [comment] 2015-07-15 17:04
as you'll need to provide a day and time in your events, you should instruct the weekview to go to the right day, otherwise the events won't be visible.

**Comment by anobilisgorse** [comment] 2015-07-19 14:45
I'm sorry @marunjar  and @caske33, I tried it but I think you misunderstood something.

I like it to be a one Day View as shown here
![class schedule](https://cloud.githubusercontent.com/assets/8383878/8766351/16a315b4-2e67-11e5-8732-47b0ab53189a.jpg)

So if I set it to xScrollingSpeed to 0 and noOfVisibleDays to 7, it would show a seven Day View, but non scrollable. 

What I am aiming is a scrollable one Day View, but stops before Sunday and after Saturday.

**Comment by caske33** [comment] 2015-07-19 15:12
That's currently not possible.

**Comment by lolobosse** [comment] 2015-07-28 22:57
It is but you have to mod the lib itself...

I assume that you can check the current day in the `touchListener` so you can basically cancel all effect of this listener in a given direction for a given day. Did I miss something @caske33 (yes, I'm back in the business, exams are over!)

**Comment by alamkanak** [comment] 2015-07-29 00:49
Duplicate of #6

**Closed by alamkanak** 2015-07-29 00:49 UTC

**Comment by caske33** [comment] 2015-08-05 12:53
Not sure @lolobosse. I think that could do it, but there is also the swing which might make it go over the edge, I think.

**Comment by YeisonGomez** [comment] 2017-01-16 16:29
Hi, This has already been implemented?
