### ISSUE TITLE
problem in show event in between day

### ISSUE THREAD

**Issue by siavash-sajjad** [alamkanak/Android-Week-View#176] opened 2015-09-14 17:41 UTC
Hi everyone.
i defined new event from today to 2 day latter like code below:

WeekViewEvent weekViewEvent = new WeekViewEvent(1,"test",2015,9,14,17,17,2015,9,16,9,10);

but in the calendar view not show event in 2015/9/15 date

![test](https://cloud.githubusercontent.com/assets/7326251/9857013/651f3414-5b2d-11e5-9c74-e8569dbf1c2a.png)

**Comment by caske33** [comment] 2015-09-14 18:36
Duplicate of #150

**Closed by caske33** 2015-09-14 18:36 UTC

**Comment by siavash-sajjad** [comment] 2015-09-14 19:15
Thank you. but i don't find solution for my problem.

**Comment by caske33** [comment] 2015-09-14 20:08
Pull Request #151 should fix this, but @alamkanak has to merge this first before this becomes live.
