### ISSUE TITLE
Not all overlapping events are displayed

### ISSUE THREAD

**Issue by DrAndroid** [alamkanak/Android-Week-View#165] opened 2015-08-08 14:44 UTC
I want to display some overlapping events. 2 of them (blue & yellow) are displayed correctly, but if I want to display the 3rd (grey) overlapping event, some of the others are not displayed. Is there any workaround for this problem? 

![1](https://cloud.githubusercontent.com/assets/13708360/9150825/c6826902-3df4-11e5-95e6-cf767f3805d8.png)
![2](https://cloud.githubusercontent.com/assets/13708360/9150826/c68336e8-3df4-11e5-9df5-451cf81567ab.png)

**Comment by caske33** [comment] 2015-08-08 14:54
Seems like a duplicate of #115. Should have been fixed by #116 normally. 

@DrAndroid  What version of the library are you using?

**Comment by lolobosse** [comment] 2015-08-11 21:44
@DrAndroid @caske33 it seems to be a dupplicate but it could be that my fix is not properly running :anguished:, can you post your code?

**Comment by mkaczma** [comment] 2015-08-13 07:05
I have the same problem, here is my onMonthChange:

    @Override
	public List<WeekViewEvent> onMonthChange(int newYear, int newMonth) {
		List<WeekViewEvent> events = new ArrayList<WeekViewEvent>();
		if (Calendar.getInstance().get(Calendar.MONTH) == newMonth) {
			Calendar startTime = Calendar.getInstance();
			startTime.set(Calendar.HOUR_OF_DAY, 8);
			startTime.set(Calendar.MINUTE, 0);
			startTime.set(Calendar.MONTH, newMonth);
			startTime.set(Calendar.YEAR, newYear);
			Calendar endTime = (Calendar) startTime.clone();
			endTime.set(Calendar.HOUR_OF_DAY, 16);
			endTime.set(Calendar.MINUTE, 0);
			endTime.set(Calendar.MONTH, newMonth);
			endTime.set(Calendar.YEAR, newYear);
			WeekViewEvent event = new WeekViewEvent(1, "Today", startTime, endTime);
			event.setColor(Color.YELLOW);
			events.add(event);

			startTime = Calendar.getInstance();
			startTime.set(Calendar.HOUR_OF_DAY, 9);
			startTime.set(Calendar.MINUTE, 0);
			startTime.set(Calendar.MONTH, newMonth);
			startTime.set(Calendar.YEAR, newYear);
			endTime = (Calendar) startTime.clone();
			endTime.set(Calendar.HOUR_OF_DAY, 9);
			endTime.set(Calendar.MINUTE, 30);
			endTime.set(Calendar.MONTH, newMonth);
			endTime.set(Calendar.YEAR, newYear);
			event = new WeekViewEvent(2, "Task 1", startTime, endTime);
			event.setColor(Color.RED);
			events.add(event);

			startTime = Calendar.getInstance();
			startTime.set(Calendar.HOUR_OF_DAY, 11);
			startTime.set(Calendar.MINUTE, 0);
			startTime.set(Calendar.MONTH, newMonth);
			startTime.set(Calendar.YEAR, newYear);
			endTime = (Calendar) startTime.clone();
			endTime.set(Calendar.HOUR_OF_DAY, 12);
			endTime.set(Calendar.MINUTE, 0);
			endTime.set(Calendar.MONTH, newMonth);
			endTime.set(Calendar.YEAR, newYear);
			event = new WeekViewEvent(3, "Task 2", startTime, endTime);
			event.setColor(Color.BLUE);
			events.add(event);
		}

		return events;
	}

**Comment by caske33** [comment] 2015-08-13 07:07
@mkaczma what version of the library are you using?

**Comment by mkaczma** [comment] 2015-08-13 07:09
1.2.3

**Comment by mkaczma** [comment] 2015-08-13 11:50
When is use library from maven repository I have this problem, but when I use library from develop branch all events are displayed OK.

**Comment by caske33** [comment] 2015-08-13 19:18
@alamkanak Can you release the latest commit to maven then?

**Comment by caske33** [comment] 2016-01-03 10:17
@mkaczma This should normally be solved since 1.2.4 thanks to #116

**Closed by caske33** 2016-01-03 10:17 UTC
