### ISSUE TITLE
I am using alamkanak library and I want that user cant see days beyond 15 days from today and the hours should be from 5 am to 11 pm

### ISSUE THREAD

**Issue by Swapnil-Garg16** [alamkanak/Android-Week-View#218] opened 2015-12-07 12:40 UTC
I am using alamkanak library and I want that user cant see days beyond 15 days from today and the hours should be from 5 am to 11 pm

**Comment by caske33** [comment] 2015-12-07 12:51
That's currently not possible yet. 

Duplicate of #85

**Closed by caske33** 2015-12-07 12:51 UTC
